#!/bin/bash
#
# Author: schadix (copied sceleton from jonesy@cs.princeton.edu)
#
# chkconfig: 2345 13 100
# description: tweet-to-S3
# NEW VERSION FROM (http://www.linux.com/learn/tutorials/442412-managing-linux-daemons-with-init-scripts)

# Source function library.
. /etc/init.d/functions

# Activate the python virtual environment
. /home/ec2-user/python27/bin/activate

TWEET_TO_S3_HOME=/home/ec2-user/tweet-to-S3
SERVICENAME=tweet-to-S3

case "$1" in
    start)
        echo -n "Starting $SERVICENAME services: "
        cd $TWEET_TO_S3_HOME
        nohup daemon python collector.py &
        touch /var/lock/subsys/$SERVICENAME
    ;;
    stop)
        echo -n "Shutting down $SERVICENAME services: "
        killproc $SERVICENAME
        rm -f /var/lock/subsys/$SERVICENAME
    ;;
    status)
        status $SERVICENAME
    ;;
    restart)
        $0 stop; $0 start
    ;;
    reload)
        $0 stop; $0 start
    ;;
    *)
        echo "Usage: $SERVICENAME {start|stop|status|reload|restart[|probe]"
        exit 1
    ;;
esac
