#! /bin/bash
# Copyright (c) 1996-2012 My Company.
# All rights reserved.
#
# Author: Bob Bobson, 2012
#
#
# chkconfig: 2345 80 50
# description:  read tweets and store them in S3
#
### BEGIN INIT INFO
# Provides: tweet-to-S3
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Test daemon process
# Description:    Runs up the test daemon process
### END INIT INFO

# Activate the python virtual environment
    . /home/ec2-user/python27/bin/activate

TWEET_TO_S3_HOME=/home/ec2-user/tweet-to-S3

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    cd $TWEET_TO_S3_HOME
    python collector.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    cd $TWEET_TO_S3_HOME
    python collector.py stop
    ;;
  restart)
    echo "Restarting server"
    cd $TWEET_TO_S3_HOME
    python collector.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/tweet-to-S3.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
